// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations usam a conexão session-mode (5432). Cai no DATABASE_URL
    // quando DIRECT_URL não está definido (ex.: Postgres local).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
